from fastapi import FastAPI, Request, BackgroundTasks
from langchain_google_genai import ChatGoogleGenerativeAI
from github_helper import get_installation_access_token, post_comment
import requests
import datetime
import os

app = FastAPI(title="Lyzr AI Backend Challenge")

# --- GLOBAL STORAGE FOR LOGS ---
logs = []

def run_ai_review(diff_url, pr_number, repo_full_name, installation_id):
    print(f"\n{'='*50}")
    print(f"🚀 PROCESSING PR #{pr_number} for {repo_full_name}")
    print(f"{'='*50}")

    # 1. Fetch Diff
    token = get_installation_access_token(installation_id)
    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github.v3.diff"}
    api_diff_url = f"https://api.github.com/repos/{repo_full_name}/pulls/{pr_number}"
    
    try:
        diff_resp = requests.get(api_diff_url, headers=headers)
        diff_resp.raise_for_status()
        diff_data = diff_resp.text
    except Exception as e:
        print(f"❌ Error fetching diff: {e}")
        return

    # 2. AI Analysis (Strict Tech Lead Persona)
    print("🧠 Sending to Google Gemini for analysis...")
    
    # Using the stable Gemini model
    llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0.2)
    
    prompt = f"""
    You are a cynical Senior Backend Engineer. Review this code diff.
    
    Output Style:
    1. Start immediately with a VERDICT: either "🔴 CHANGES REQUESTED" or "🟢 APPROVED".
    2. Provide a 1-sentence summary of what the code does.
    3. List only CRITICAL issues (Security, O(n^2) performance, Data Loss).
    4. Be extremely concise. No fluff. No "In conclusion". 
    5. Show a specific code snippet fix for the worst issue.
    
    If the code is safe, just say "🟢 APPROVED" and "Looks good to me."
    
    DIFF:
    {diff_data[:8000]}
    """
    
    try:
        review = llm.invoke(prompt).content
        print("✅ Analysis Complete!")
    except Exception as e:
        review = f"AI Error: {str(e)}"
        print(f"❌ AI Failed: {e}")

    # 3. Post Comment
    final_comment = f"## 🤖 Lyzr AI Code Review\n\n{review}\n\n*Generated by Pushkar Sahu's Agent*"
    post_comment(repo_full_name.split("/")[0], repo_full_name.split("/")[1], pr_number, token, final_comment)
    
    # 4. Save Logs
    logs.insert(0, {
        "timestamp": datetime.datetime.now().strftime("%H:%M:%S"),
        "pr_id": pr_number,
        "repo": repo_full_name,
        "status": "✅ Reviewed" if "Error" not in review else "❌ Failed",
        "summary": review,
        "lines_analyzed": len(diff_data.splitlines())
    })

@app.post("/webhook")
async def handle_webhook(request: Request, background_tasks: BackgroundTasks):
    payload = await request.json()
    action = payload.get("action")
    
    print(f"🔔 Webhook Received. Action: {action}")
    
    if action in ["opened", "synchronize", "reopened"]:
        pr = payload["pull_request"]
        installation_id = payload.get("installation", {}).get("id")
        
        background_tasks.add_task(
            run_ai_review, 
            pr["diff_url"], 
            pr["number"], 
            payload["repository"]["full_name"],
            installation_id
        )
        return {"status": "Review Queued"}
    
    return {"status": "Ignored"}

# --- THIS IS THE MISSING PART THAT CAUSED 404 ---
@app.get("/logs")
def get_logs():
    return logs